name: Mirror to GitLab

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/milestone-hackathon/${{ github.event.repository.name }}.git
          git push gitlab --all --force
          git push gitlab --tags --force
